# Mago configuration file
# For more information, see https://mago.carthage.software/#/getting-started/configuration
php_version = "8.4.0"

[source]
paths = ["src/", "tests/"]
includes = ["vendor"]
excludes = [
    "./vendor/symfony/cache/Traits/ValueWrapper.php",
    "./vendor/composer",
]

[format]
print_width = 120
tab_width = 4
use_tabs = false

[linter]
default_plugins = true
plugins = ["php-unit"]

# NAMING
[[linter.rules]]
name = "naming/interface"
psr = false

[[linter.rules]]
name = "naming/trait"
psr = false

[[linter.rules]]
name = "naming/class"
psr = false

# STRICTNESS

[[linter.rules]]
name = "strictness/require-parameter-type"
ignore_arrow_function = true
ignore_closure = true

[[linter.rules]]
name = "strictness/require-return-type"
ignore_arrow_function = true
ignore_closure = true

[[linter.rules]]
name = "analysis/override-attribute"
level = "off"

[[linter.rules]]
name = "maintainability/halstead"
level = "off"

[[linter.rules]]
name = "maintainability/too-many-methods"
level = "off"

[[linter.rules]]
name = "maintainability/kan-defect"
level = "off"

[[linter.rules]]
name = "maintainability/cyclomatic-complexity"
level = "off"